before_script:
    - uname -a
    - sudo apt-get install apache2
    - wget -O /tmp/pukiwiki.tar.gz "http://sourceforge.jp/frs/redir.php?m=osdn&f=%2Fpukiwiki%2F12957%2Fpukiwiki-1.4.7_notb.tar.gz"
    - (cd /tmp; tar xvzf pukiwiki.tar.gz)
    - chmod 777 /tmp/pukiwiki-1.4.7_notb/attach
    - chmod 777 /tmp/pukiwiki-1.4.7_notb/backup
    - chmod 777 /tmp/pukiwiki-1.4.7_notb/cache
    - chmod 777 /tmp/pukiwiki-1.4.7_notb/counter
    - chmod 777 /tmp/pukiwiki-1.4.7_notb/diff
    - chmod 755 /tmp/pukiwiki-1.4.7_notb/image
    - chmod 755 /tmp/pukiwiki-1.4.7_notb/image/face
    - chmod 755 /tmp/pukiwiki-1.4.7_notb/lib
    - chmod 755 /tmp/pukiwiki-1.4.7_notb/plugin
    - chmod 755 /tmp/pukiwiki-1.4.7_notb/skin
    - chmod 777 /tmp/pukiwiki-1.4.7_notb/trackback
    - chmod 777 /tmp/pukiwiki-1.4.7_notb/wiki
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/.htaccess
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/.htpasswd
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/*/.htaccess
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/*.php
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/*/*.php
    - chmod 666 /tmp/pukiwiki-1.4.7_notb/attach/*
    - chmod 666 /tmp/pukiwiki-1.4.7_notb/backup/*.txt
    - chmod 666 /tmp/pukiwiki-1.4.7_notb/cache/*
    - chmod 666 /tmp/pukiwiki-1.4.7_notb/counter/*
    - chmod 666 /tmp/pukiwiki-1.4.7_notb/diff/*.txt
    - chmod 666 /tmp/pukiwiki-1.4.7_notb/wiki/*.txt
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/image/*
    - chmod 755 /tmp/pukiwiki-1.4.7_notb/image/face
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/image/face/*
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/lib/*
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/plugin/*
    - chmod 644 /tmp/pukiwiki-1.4.7_notb/skin/*
    - cat /etc/apache2/apache2.conf
    - echo "=="
    - cat /etc/apache2/httpd.conf
after_faulure:
    - cat /tmp/vimlint_test.log
 
